### ISSUE TITLE
patch method seems broken

### ISSUE THREAD

**Issue by sbnedkov** [winduptoy/mongoose-json-patch#6]
Hi,

Is it just me or a missing ```self``` in from of ```writeBlacklist``` breaks patch?

Cheers.

**Comment by winduptoy** [comment]
@sbnedkov Oops! Try v1.1.1 and let me know if that fixed it for you.

**Comment by sbnedkov** [comment]
@winduptoy , it is fixed now and I'm using the 1.1.1 version, thanks for the quick intervention. Closing.
